import localFont from "next/font/local";
import Link from "next/link";
import "./globals.css";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={ `${geistSans.variable} ${geistMono.variable} mx-auto max-w-screen-lg px-4   antialiased`}
      >
        <nav className="flex justify-between items-center ">
          <Link  href="/">
          logo

          </Link>
          <ul className="flex space-x-4 m-5">
            <li>
              <Link href="/contact"> conatct</Link>
            </li>
            <li>
              <Link href="/about">about</Link>
            </li>
          </ul>
        </nav>
      
        {children }
     
    
      </body> 
    </html>
  );
}
